### ISSUE TITLE
Documentation as text

### ISSUE THREAD

**Issue by brean** [HoangGiang93/urdf_importer#5]
Instead of an uncommented video also add the installation steps as text.

**Comment by brean** [comment]
...for debugging I also like to just link the source folder into .config/blender/plugins which is also nice to add to the documentation

**Comment by HoangGiang93** [comment]
I thought the video is the most intuitive way to visualize the installation. Why do you need them as text?

**Comment by brean** [comment]
The idea of having a video is nice but I think its not easy to follow.
The video is too small to read text, so I need to view it in fullscreen, I to pause the video, switch to my terminal, enter the command there, switch back to the terminal, continue the video... just copy-pasting the commands from a list of text that also explain why you do what would be easier.
Also the video does not explain what is happening so for example sourcing noetic could be confusing for a very new user who is using ros2 and Blender for the first time and they might be in a completely different environment, so just a list of comments with text explaining it and maybe some screenshots would be a lot better to follow I think.
And most students only have a notebook without a second screen so they need to switch from the video to the terminal back-and-forth. With just text you can easily have it on one side of the screen and the terminal on the other.
