### ISSUE TITLE
How can i use this tool in command line instead of blender ui

### ISSUE THREAD

**Issue by PiggyGaGa** [HoangGiang93/urdf_importer#7]
Nice work, I want to use this tool just in command line, how can I do that?

**Comment by HoangGiang93** [comment]
Thank you for your question. Actually I don't know how to do it exactly, but you could try to learn how to use command line to import and export a simple mesh file using ChatGPT, and try to replace those functions with mine. Hope it helps.

**Comment by PiggyGaGa** [comment]
Thanks a lot, according to your suggestion, I found a rep [3d-converter-py](https://github.com/leofaraf/3d-converter-py.git), which can export a simple stl file to fbx using python script, I think the core of your work is "how to construct robot according to ros information, and reconstruct isolated mesh into whole body robot in fbx", that is why I have to source my ros setup.bash in when using this tool.
if I want to convert urdf into fbx, I think the bellow steps are needed:
- load meshes using python bpy
- convert single stl into fbx
- combine all fbx files intor robot fbx fomat
- export fbx in python cmd.

**Comment by PiggyGaGa** [comment]
After some changes, I have already improve this tool into a comand line tool, which do not need blender ui. Thanks a lot.

**Comment by HoangGiang93** [comment]
Cool! I'm glad that it worked
